### PR TITLE
Re-establish correct nuget packaging

### LINKED ISSUE #6: Don't install 2.0.0.1
I have next problem

```
Could not install package 'Xamarin.TTTAttributedLabel 2.0.0.1'. You are trying to install this package into a project that targets 'Xamarin.iOS,Version=v1.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
```

Version 2.0.0.0 installed without problem.

### PR DESCRIPTION
**Pull request by AliakseiT**
I hope, it should close #6.

UPD: enabled bitcode in building the original libraries - you can't submit an app without it these days.

### CODE REVIEW

**Comment by michaeldwan** [comment]
Ran into this as well. Thanks for the fix.

**Comment by jphenow** [comment]
Bump? Would be cool to get this upstream in nuget

**Comment by AliakseiT** [comment]
@colbylwilliams, could you please merge?

**Comment by colbylwilliams** [comment]
@AliakseiT @jphenow sorry for the silence and and thanks for the PR.  I'll try to get an updated nuget published this weekend.

**Comment by Falgantil** [comment]
Any news on this? My team is also running into this exact issue when building on VS for Mac

**Comment by ncruces** [comment]
Can confirm that this PR works. Hopefully, @colbylwilliams, you can publish the updated package.

**Comment by colbylwilliams** [comment]
@michaeldwan @jphenow @Falgantil @ncruces new package pushed to NuGet (v2.0.0.2).  Sorry again for the delay, and thanks a bunch @AliakseiT for your PR.

**Comment by michaeldwan** [comment]
Thanks @colbylwilliams!

**Pull request merged**
